import "~/styles/globals.css";

import { type Metadata } from "next";
import {Poppins} from "next/font/google";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const pops = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
    // weight: ["400"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${pops.className} dark`}>
      <body>
       <main className={'px-32 py-16'}>
           <TRPCReactProvider>{children}</TRPCReactProvider>
       </main>
      </body>
    </html>
  );
}
